### ISSUE TITLE
Links to function line numbers

### ISSUE THREAD

**Issue by jmassara** [davecheney/godoc2md#11]
When you click the link to a function, it is 10 lines off from the location within the source file.

**Comment by davecheney** [comment]
I'm unlikely to fix this at this point. If you want to take a crack, PR's
welcome.

**Comment by kenjones-cisco** [comment]
@jmassara Seems the problem is related to godoc.
https://github.com/golang/tools/blob/master/godoc/godoc.go#L549
For some reason it always subtracts 10 from the line number.

The good news, godoc provides a way to override that by providing your own function to the Presentation that can be used to return a different representation. `Presentation.URLForSrcPos` which is of type `func(src string, line, low, high int) string`
